# -*- coding: utf-8 -*-
"""machine_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHfuWC5SyDgIoYsPrCV108QRWd2X8Rfz
"""

import streamlit as st
import joblib
import pandas as pd

model = joblib.load("lr_model.pkl")

st.title("machine failure prediction !")

footfall = st.number_input("footfall")
tempMode = st.number_input("tempMode")
AQ = st.number_input("AQ")
USS = st.number_input("USS")
CS = st.number_input("CS")
VOC = st.number_input("VOC")
 RP = st.number_input("RP")
 IP = st.number_input("IP")
Temperature = st.number_input("Temperature")
 fail = st.number_input("fail")

input_data = pd.DataFrame({
    "footfall": [footfall],
    "tempMode": [tempMode],
    "AQ": [AQ],
    "USS": [USS],
    "CS": [CS],
    "VOC": [VOC],
    "RP": [RP],
    "IP": [IP],
    "Temperature": [Temperature],
    "fail": [fail]
})

if st.button("Predict"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("Machine Failure Detected!")
    else:
        st.success("No Machine Failure Detected.")
